### ISSUE TITLE
Python 3.5 compatibility

### ISSUE THREAD

**Issue by thomasmost** [jsfehler/stere#178]
Hey @jsfehler,

I'm trying to run stere in a `pipenv` virtual environment with Python 3.5, and running into a weird error. I haven't really touched Python since college, so I'm wondering if this will make more sense to you:

```
Traceback (most recent call last):
  File "e2e/e2e.py", line 1, in <module>
    from stere import Stere
  File "/Users/thomas/.local/share/virtualenvs/main-BeZBXvMj/lib/python3.5/site-packages/stere/__init__.py", line 1, in <module>
    from .browserenabled import BrowserEnabled as Stere
  File "/Users/thomas/.local/share/virtualenvs/main-BeZBXvMj/lib/python3.5/site-packages/stere/browserenabled.py", line 8
    file_path = f'{cwd}/stere.ini'
                                 ^
SyntaxError: invalid syntax
```

Should stere be compatible with Python 3.5?

**Comment by jsfehler** [comment]
Only 3.6 and up. The error you're getting is due to the use of f-strings: https://realpython.com/python-f-strings/

**Comment by thomasmost** [comment]
Thanks -- opened a PR to add that to the README

**Comment by thomasmost** [comment]
oh, shoot me in the face, it's right at the top of the damn README
